### ISSUE TITLE
python setup.py install works as intended?

### ISSUE THREAD

**Issue by lebigot** [CFMTech/Jupytab#1]
On my machine, I had to do [pip ->] python setup.py install notetab twice in order to install notetab…

PS: I actually meant "python setup.py install" in the source directory.

**Comment by YannHirou** [comment]
works fine for me
- python 3.6.7
- pip 19.2.1
(fresh virtualenv on ubuntu 18.04.2 LTS)

**Comment by faulaire** [comment]
Works fine for me too.

- Python 3.7.2
- pip 19.0.3

Using ubuntu (Windows Subsystem for Linux)

**Comment by lebigot** [comment]
I'm closing this issue, then. Thanks for checking!

**Comment by lebigot** [comment]
PS: I actually meant "python setup.py install" in the source directory, so I'm reopening this. I updated the original issue.

**Comment by faulaire** [comment]
It's also works with "python setup.py install" on my environment.

**Comment by lebigot** [comment]
Even a fresh and mostly "empty" environment? The first time I tried, it pulled ans installed many packages but did not install NoteTab, and the second time it installed it.

**Comment by faulaire** [comment]
Yes, I just tried to create an empty environment and it works. (ps : I used a conda environment to perform the test).

**Comment by lebigot** [comment]
Thanks. I'll try to reproduce this, then, and will report back.

**Comment by btribonde** [comment]
Has been tested with fresh install and notebook never seen before from execution. No problem to install jupytab with pip. I think this issue could be closed. 
Regards

**Comment by lebigot** [comment]
As I was saying above, the problem I (think I) saw was actually on "python setup.py install", not pip (I just fixed the title). It's not a huge issue in any case, but it is still open: the setup.py test should be done again.

**Comment by btribonde** [comment]
python setup is working fine now :)
