### ISSUE TITLE
Jupytab not working on Windows (SIGUP issue)

### ISSUE THREAD

**Issue by bansalpulkit** [CFMTech/Jupytab#22]
Hi

I followed the instructions under Readme however when connecting to the sample data source of AirFlights, tableau takes forever to connect and had to be cancelled after a long wait. Can you please help guide if I am going something wrong. Here is the output from console:
Start notebook ./AirFlights.ipynb on 127.0.0.1:53150
Start notebook ./RealEstateCrime.ipynb on 127.0.0.1:53151
Start notebook ./TaboolaCampaignSummary.ipynb on 127.0.0.1:53152
Your token is 02014868fe0eef123269397c5bc65a9608b3cedb73e3b84d8d02c220
        Please open : http://INEITS-MLAP-156:8765/?security_token=02014868fe0eef123269397c5bc65a9608b3cedb73e3b84d8d02c220
INFO:[KernelGatewayApp] Kernel started: e6efb1ab-a544-4ed3-9a3b-b34eafb2b795
INFO:[KernelGatewayApp] Kernel started: 4e2effed-d520-41c4-a7e3-c18ffeda64a2
INFO:[KernelGatewayApp] Kernel started: 13a0fc6a-0a4a-49d4-99f0-4228d8d85fc9
INFO:200 GET /api?security_token=02014868fe0eef123269397c5bc65a9608b3cedb73e3b84d8d02c220 (fe80::a5d6:426f:c457:97b9) 1.00ms
http://127.0.0.1:53150/schema
INFO:[KernelGatewayApp] Registering resource: /schema, methods: (['GET'])
INFO:[KernelGatewayApp] Registering resource: /data, methods: (['GET'])
INFO:[KernelGatewayApp] Registering resource: /_api/spec/swagger.json, methods: (GET)
INFO:[KernelGatewayApp] Jupyter Kernel Gateway at http://127.0.0.1:53151
INFO:Traceback (most recent call last):
INFO:  File "c:\program files (x86)\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
INFO:    "__main__", mod_spec)
INFO:  File "c:\program files (x86)\python\python37-32\lib\runpy.py", line 85, in _run_code
INFO:    exec(code, run_globals)
INFO:  File "C:\Program Files (x86)\Python\Python37-32\Scripts\jupyter-kernelgateway.EXE\__main__.py", line 7, in <module>
INFO:  File "c:\program files (x86)\python\python37-32\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
INFO:    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
INFO:  File "c:\program files (x86)\python\python37-32\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
INFO:    app.start()
INFO:  File "c:\program files (x86)\python\python37-32\lib\site-packages\kernel_gateway\gatewayapp.py", line 549, in start
INFO:    signal.signal(signal.SIGHUP, signal.SIG_IGN)
INFO:AttributeError: module 'signal' has no attribute 'SIGHUP'
ERROR:Uncaught exception GET /kernel/AirFlights/schema?security_token=02014868fe0eef123269397c5bc65a9608b3cedb73e3b84d8d02c220 (fe80::a5d6:426f:c457:97b9)
HTTPServerRequest(protocol='http', host='ineits-mlap-156:8765', method='GET', uri='/kernel/AirFlights/schema?security_token=02014868fe0eef123269397c5bc65a9608b3cedb73e3b84d8d02c220', version='HTTP/1.1', remote_ip='fe80::a5d6:426f:c457:97b9')
Traceback (most recent call last):
  File "c:\program files (x86)\python\python37-32\lib\site-packages\tornado\web.py", line 1678, in _execute
    result = await result
  File "c:\program files (x86)\python\python37-32\lib\site-packages\jupytab\jupytab_api.py", line 126, in prepare
    response = await AsyncHTTPClient().fetch(request)
ConnectionRefusedError: [Errno 10061] Unknown error
ERROR:500 GET /kernel/AirFlights/schema?security_token=02014868fe0eef123269397c5bc65a9608b3cedb73e3b84d8d02c220 (fe80::a5d6:426f:c457:97b9) 1021.27ms
INFO:[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
INFO:[KernelGatewayApp] Registering resource: /schema, methods: (['GET'])
INFO:[KernelGatewayApp] Registering resource: /data, methods: (['GET'])
INFO:[KernelGatewayApp] Registering resource: /_api/spec/swagger.json, methods: (GET)
INFO:[KernelGatewayApp] Jupyter Kernel Gateway at http://127.0.0.1:53150
INFO:Traceback (most recent call last):
INFO:  File "c:\program files (x86)\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
INFO:    "__main__", mod_spec)
INFO:  File "c:\program files (x86)\python\python37-32\lib\runpy.py", line 85, in _run_code
INFO:    exec(code, run_globals)
INFO:  File "C:\Program Files (x86)\Python\Python37-32\Scripts\jupyter-kernelgateway.EXE\__main__.py", line 7, in <module>
INFO:  File "c:\program files (x86)\python\python37-32\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
INFO:    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
INFO:  File "c:\program files (x86)\python\python37-32\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
INFO:    app.start()
INFO:  File "c:\program files (x86)\python\python37-32\lib\site-packages\kernel_gateway\gatewayapp.py", line 549, in start
INFO:    signal.signal(signal.SIGHUP, signal.SIG_IGN)
INFO:AttributeError: module 'signal' has no attribute 'SIGHUP'
INFO:[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
INFO:[KernelGatewayApp] Registering resource: /schema, methods: (['GET'])
INFO:[KernelGatewayApp] Registering resource: /data, methods: (['GET'])
INFO:[KernelGatewayApp] Registering resource: /_api/spec/swagger.json, methods: (GET)
INFO:[KernelGatewayApp] Jupyter Kernel Gateway at http://127.0.0.1:53152
INFO:Traceback (most recent call last):
INFO:  File "c:\program files (x86)\python\python37-32\lib\runpy.py", line 193, in _run_module_as_main
INFO:    "__main__", mod_spec)
INFO:  File "c:\program files (x86)\python\python37-32\lib\runpy.py", line 85, in _run_code
INFO:    exec(code, run_globals)
INFO:  File "C:\Program Files (x86)\Python\Python37-32\Scripts\jupyter-kernelgateway.EXE\__main__.py", line 7, in <module>
INFO:  File "c:\program files (x86)\python\python37-32\lib\site-packages\jupyter_core\application.py", line 266, in launch_instance
INFO:    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
INFO:  File "c:\program files (x86)\python\python37-32\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
INFO:    app.start()
INFO:  File "c:\program files (x86)\python\python37-32\lib\site-packages\kernel_gateway\gatewayapp.py", line 549, in start
INFO:    signal.signal(signal.SIGHUP, signal.SIG_IGN)
INFO:AttributeError: module 'signal' has no attribute 'SIGHUP'
INFO:[IPKernelApp] WARNING | Parent appears to have exited, shutting down.

Thanks
Pulkit

**Comment by btribonde** [comment]
Hi @bansalpulkit,

Thanks for creating an issue.

According to [Jupyter Kernel Gateway issue 325](https://github.com/jupyter/kernel_gateway/pull/325)

This will be fixed in the next release of jupyter kernel gateway (2.5.0). Could you tell me which version  are you currently using ?

Regards

**Comment by bansalpulkit** [comment]
i am running 2.4.0

**Comment by bansalpulkit** [comment]
seems it is not able to get the schema definition, I have tried running the AirFlights.ipynb file individually in jupyter and able to get the schema successfully

**Comment by bansalpulkit** [comment]
I was able to resolve the issue by commenting  the following command in the gatewayapp.py script

#signal.signal(signal.SIGHUP, signal.SIG_IGN)

Thanks for your help anyways :)

**Comment by btribonde** [comment]
This is the fix they have done for the future 2.5.0 release ;)

Is it working in Tableau now ?

**Comment by bansalpulkit** [comment]
yup works like a charm

**Comment by btribonde** [comment]
Thanks for your feedback.

I keep the issue open for other people (just renamed it a bit), and will be closed when jupyter kernel gateway releases their new version

**Comment by tardis123** [comment]
@bansalpulkit,

thanks for your workaround.
Ran into the same issue today and your workaround fixed it.

Thanks!

**Comment by btribonde** [comment]
Hello @bansalpulkit @tardis123 
New version of Jupiter kernel gateway has been released that should fix this issue (2.4.1)

**Comment by arpitgupta1995** [comment]
Hi @bansalpulkit,
I am also trying to run JupyTab but can't connect. Do you have any other resources which you think might be useful in creating a connection.
I am facing issues with the config file and Notebook preparation.
