### ISSUE TITLE
Capability for SSL

### ISSUE THREAD

**Issue by rleyba828** [CFMTech/Jupytab#24]
Hi,
   We would like to request a feature to have the traffic to/from tableau be over SSL? 

thanks

-rleyba

**Comment by btribonde** [comment]
Hello

New version 0.9.4 include this feature, could you give it a try ?

https://pypi.org/project/jupytab/0.9.4/
https://pypi.org/project/jupytab-server/0.9.4/

You need to add the following to your config file in main section

[main]
ssl_enabled = True
ssl_key = /etc/pki/tls/certs/file.crt
ssl_cert = /etc/pki/tls/private/file.key

**Comment by btribonde** [comment]
Just figured out that protocol https was used between internal (http) and external (https) request.

Will need to create a 0.9.5 version to fix this.

**Comment by btribonde** [comment]
Version 0.9.5 delivered, seems ok to me
