### ISSUE TITLE
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 83062: character maps to <undefined>

### ISSUE THREAD

**Issue by gibranhasan14** [CFMTech/Jupytab#27]
I'm running on Windows 10
After running jupytab --config=config.ini in Anaconda Prompt
I get the following error:

INFO:Traceback (most recent call last):
INFO:  File "c:\users\ghasan\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
INFO:    "__main__", mod_spec)
INFO:  File "c:\users\ghasan\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
INFO:    exec(code, run_globals)
INFO:  File "C:\Users\ghasan\AppData\Local\Continuum\anaconda3\Scripts\jupyter-kernelgateway.EXE\__main__.py", line 9, in <module>
INFO:  File "c:\users\ghasan\appdata\local\continuum\anaconda3\lib\site-packages\jupyter_core\application.py", line 267, in launch_instance
INFO:    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
INFO:  File "c:\users\ghasan\appdata\local\continuum\anaconda3\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
INFO:    app.initialize(argv)
INFO:  File "c:\users\ghasan\appdata\local\continuum\anaconda3\lib\site-packages\kernel_gateway\gatewayapp.py", line 381, in initialize
INFO:    self.init_configurables()
INFO:  File "c:\users\ghasan\appdata\local\continuum\anaconda3\lib\site-packages\kernel_gateway\gatewayapp.py", line 400, in init_configurables
INFO:    self.seed_notebook = self._load_notebook(self.seed_uri)
INFO:  File "c:\users\ghasan\appdata\local\continuum\anaconda3\lib\site-packages\kernel_gateway\gatewayapp.py", line 356, in _load_notebook
INFO:    notebook = nbformat.read(nb_fh, 4)
INFO:  File "c:\users\ghasan\appdata\local\continuum\anaconda3\lib\site-packages\nbformat\__init__.py", line 141, in read
INFO:    return reads(fp.read(), as_version, **kwargs)
INFO:  File "c:\users\ghasan\appdata\local\continuum\anaconda3\lib\encodings\cp1252.py", line 23, in decode
INFO:    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
INFO:UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 83062: character maps to <undefined>

The notebook runs just fine when I run it myself

**Comment by btribonde** [comment]
Hello,

According to other issues like this one (https://github.com/jupyter/nbconvert/issues/742, https://github.com/fastai/course-v3/issues/397 or https://stackoverflow.com/questions/49562499/how-to-fix-unicodedecodeerror-charmap-codec-cant-decode-byte-0x9d-in-posit) this seems to be an issue easy to solve, linked to how nbformat reads the notebook.

Could you send me a copy of your notebook so I could test which changes would work on windows ?

**Comment by gibranhasan14** [comment]
Unfortunately I can't send it bc it has confidential data, I can tell you I'm using an oracle SQL Client
(cx_Oracle) and (simple_salesforce). 
When I run it on my mac it works but only with static data, it stops working when I use the refresh_method. Since some of the API client connections need to be refreshed when the session dies, should I be adding in all the imports, and instiating the clients within the function for the refresh_method or can I define them outside of it (creds are stored in the same directory as the notebook) ? 

error message on mac:

INFO:[KernelGatewayApp] Kernel started: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
http://xxxxxxxxxxxx/data?table_name=data_pull
ERROR:Uncaught exception GET /kernel/example/data?table_name=data_pull&security_token=xxxxxxxxxxxxxxxxxxxxxxxxxx (x.x.x)
HTTPServerRequest(protocol='http', host='xxxxxxxxxxx.com:xxxx', method='GET', uri='/kernel/example/data_pull?table_name=data_pull&security_token=xxxxxxxxxxxxxxxxxxxxxxxx', version='HTTP/1.1', remote_ip='x.x.x')
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.7/site-packages/tornado/web.py", line 1678, in _execute
    result = await result
  File "/opt/anaconda3/lib/python3.7/site-packages/jupytab_server/jupytab_api.py", line 126, in prepare
    response = await AsyncHTTPClient().fetch(request)
ConnectionRefusedError: [Errno 61] Connection refused
ERROR:500 GET /kernel/example/data_pull?table_name=data_pull&security_token=xxxxxxxxxxxxxxxxxxxxxxxxx(x.x.x) 3.20ms
INFO:[KernelGatewayApp] Registering resource: /schema, methods: (['GET'])
INFO:[KernelGatewayApp] Registering resource: /data, methods: (['GET'])
INFO:[KernelGatewayApp] Registering resource: /_api/spec/swagger.json, methods: (GET)
INFO:[KernelGatewayApp] Jupyter Kernel Gateway at http://xxxxxxxxxxx

**Comment by btribonde** [comment]
**Windows issue**
Could you try to create a minimal notebook, with no confidential code that still breaks ? As I understand it is probably an encoding issue, so it may break with only a few lines. And if it works, spotting the code that breaks nbformat would still be useful.

**Mac Hot reloading**
You may have a look at similar issue here: https://community.tableau.com/thread/331230
Anyway, the workflow is the following:
* At jupytab startup, your notebook is fully executed
* When tableau is asking for a refresh, it will only execute the refresh_method and is expecting a brand new dataframe as return. If you need to reconnect an API or something else you need to do this in the refresh method. The notebook is never fully executed again unless you restart the kernel.

Regards

**Comment by btribonde** [comment]
Maybe you should have a look at this issue about hot reloading : #29

**Comment by gibranhasan14** [comment]
I am working on creating a minimal notebook, I'm pretty sure I'm using the
refresh method correctly, I include all imports, instiation of API clients
including reading in my config files for my credentials, executing both the
SQL and SOQL queries (via Oracle and Simple Salesforce clients) and
generating a pandas df and
in the refresh_method function. I also use a lot of pandas merges/fuzzy
matching/cleaning so the function is over a page long.
It just takes a very long time to load the data when extract is called by
Tableau and never actually ends up populating the data. Do you think it
would make a difference if I split up the notebook in two notebooks (one
for each table)?

**Comment by btribonde** [comment]
Hello,

Don't split your notebook, it would not be very useful as each dataframe is requested separately.
Refresh method should take the same amount of time than running your notebook manually.

You can try to view data from the URI directly, replacing `/schema` by `/data?table_name=<name_of_table>` in URL (you can view the schema URL using the schema button). This could help to spot an error. If you retrieve data in json format it should also work in tableau.

I currently see two possible problems :
* Notebook computation is not ready, and never return data to tableau -> checking URL above would help to know if service is ready. Tableau seems to stuck in loading phase even if no data is returned.
* Notebook output is too large -> Currently we use json (#18) so if you try to send more than let's say a million row it may be too large.

**Comment by btribonde** [comment]
Unable to reproduce this error, and no new report of this kind

**Comment by Q-lds** [comment]
I am facing the same exact problem (for the full traceback, see https://github.com/entropicalabs/openqaoa/actions/runs/3102920694/jobs/5025695535) :

```
def test_1_workflows_example():
>       notebook_test_function("./examples/1_workflows_example.ipynb")

tests\test_notebooks.py:25: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
tests\test_notebooks.py:16: in notebook_test_function
    nb = nbformat.read(f, as_version=4)
env\lib\site-packages\nbformat\__init__.py:165: in read
    buf = fp.read()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <encodings.cp1252.IncrementalDecoder object at 0x000001EB5DF4E5E0>
input = b'{\r\n "cells": [\r\n  {\r\n   "cell_type": "markdown",\r\n   "metadata": {},\r\n   "source": [\r\n    "# Introductio...e119264b9029c842e[44](https://github.com/entropicalabs/openqaoa/actions/runs/3102920694/jobs/5025695535#step:6:45)dd4dc6168fe[45](https://github.com/entropicalabs/openqaoa/actions/runs/3102920694/jobs/5025695535#step:6:46)af36f6b571d"\r\n   }\r\n  }\r\n },\r\n "nbformat": 4,\r\n "nbformat_minor": 4\r\n}\r\n'
final = True

    def decode(self, input, final=False):
>       return codecs.charmap_decode(input,self.errors,decoding_table)[0]
E       UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position [59](https://github.com/entropicalabs/openqaoa/actions/runs/3102920694/jobs/5025695535#step:6:60)965: character maps to <undefined>
```

My function to read the notebooks is:
```
def notebook_test_function(name):

    with open(name) as f:
        nb = nbformat.read(f, as_version=4)

    ep = ExecutePreprocessor(timeout=600, kernel_name='env')

    ep.preprocess(nb)
```

And the source notebook is: https://github.com/entropicalabs/openqaoa/blob/dev_windows_tests/examples/1_workflows_example.ipynb

Using:
- nbconvert-7.0.0-py3-none-any.whl
- python 3.8
- windows-latest (through a github action)

**Comment by btribonde** [comment]
Hello Leonardo

Thanks for your feedback.

According to the stacktrace, kernel gateway (the lib used by jupytab) is trying to decode the file using the windows character set cp1252 but found some unknown chars in the notebook (so not belonging to this charset).

Could you try to encode your notebook using a different encoding ? (utf-8 or cp1252). It seems python on windows may struggle to understand the correct encoding.

Best regards

Brian TRIBONDEAU |  Executive Director - Head of Analytics - Risk & Operations Technology |  Capital Fund Management
23 rue de l'Université, 75007 Paris |  Tel : + 33 1 49 49 60 89 |  Fax: + 33 1 47 70 17 40 | ***@***.******@***.***> | cfm.fr<http://www.cfm.fr/>
This email is confidential and subject to important disclaimers available here<http://disclaimer.cfm.fr/>.

**Comment by Q-lds** [comment]
Hello there!

Indeed, you were on the right track. 

```
def notebook_test_function(name):

    with open(name, encoding='utf-8') as f:
        nb = nbformat.read(f, as_version=4)
```

Fixes the issue. Thanks!
