### ISSUE TITLE
Server not hot-reloading

### ISSUE THREAD

**Issue by dumikaiya-zz** [CFMTech/Jupytab#29]
I'm unable to hot-reload the server, I'm I missing something? Windows developer running python 3.6.8 on a virtual environment (pipenv).
When server starts and returning data properly, breaking code in jupyter later produces no error unless I restart the server manually. Essentially changing the data doesn't reflect in Tableau or browser

**Comment by btribonde** [comment]
I am not sure to understand what you mean by hot-reloading. Do you mean you have problem with the refresh_method ? Are you able to get data in Tableau with the first extract ?

Regards

**Comment by dumikaiya-zz** [comment]
@btribonde I am getting data on first extract yes. But when I change the code while the server is running, the server is not reloading nor reflecting the changes with the data. E.g:
I expect that when I remove a dataframe column from a returned dataframe and save it while the server is running, a corresponding column in Tableau should also be removed upon updating in the data source section. 
Maybe this is a unique problem for me else I'd expect others to have asked already.

**Comment by btribonde** [comment]
You can refresh a dataframe dynamically when Tableau does an extract, but notebook code is not reloaded automatically. You need to restart kernel from Jupytab UI to reflect any changes in the notebook (or restart jupytab process).

This could be a new feature like 'automatically restart notebook kernel on save', but notebook may takes some time to initialize and this could be more harmful than just clicking on restart kernel when you want your changes to be updated in Tableau.

**Comment by dumikaiya-zz** [comment]
Thank you, I have kind of a unique case where data would be updated frequently (like daily) and I would want that to be reflected automatically in Tableau when one changes dataframe's data source like csv but that is not the case. And no, I do not want to connect directly to csv from Tableau because I can do more with Python.

**Comment by btribonde** [comment]
This usecase is perfectly managed by jupytab (reexecute python code on daily tableau extract). It's just that you need to write something like that :

```
def dynamic_csv_load():
    raw_csv = pd.read_csv("daily_updated_csv") # Reload CSV file on Tableau Extract
    return raw_csv.T   # Transpose CSV file

tables = jupytab.Tables()
tables['dynamic_csv'] = jupytab.DataFrameTable('A dynamic table', refresh_method=dynamic_csv_load)
```

However, this is very different than hot-reloading of the notebook code itself. In this case your notebook code doesn't change but the csv content will be reloaded on each extract and tableau will get up to date datas.

**Comment by dumikaiya-zz** [comment]
I'm just looking at the docs, this was explained clearly in it, sorry for the inconvenience but I appreciate the help a lot. It works like a charm. I got mixed up with the static explanation in the docs.

Thanks.

**Comment by btribonde** [comment]
No problem, I probably need to improve the documentation a bit and explain more in depth how it works.
