### ISSUE TITLE
Data update always with manual workaround

### ISSUE THREAD

**Issue by deganza** [CFMTech/Jupytab#30]
Jupytab is really a great package.
But I've some problems when I'm updating the data in Jupyter Notebooks.

I'm using the following code to update dynamically the dataframe "df_country_pop_covid".
But I've always to update everything in Tableau with the following steps:

- In the "Notebook to Tableau connector" I select the notebook 
- than "restart kernel" and "Explore in Tableau"
- In the Tableau-Sheet I've to refresh the datasource

Is there not an automatic way to update the data?

##########
import jupytab
def dynamic_df_country_pop():
    return df_country_pop_covid
tables = jupytab.Tables()
tables['covid19_country_pop'] = jupytab.DataFrameTable('Covid19 Country Pop', refresh_method=dynamic_df_country_pop)

# GET /schema
tables.render_schema()

# GET /data
tables.render_data(REQUEST)
##########

**Comment by btribonde** [comment]
Hello,

Thanks for the feedback

Instead of `return df_country_pop_covid`, you need to recreate the dataframe with updated datas, jupytab can only call a method which is responsible to update dataframe.

For instance 
```
def dynamic_df_country_pop():
  return df_country_pop_covid
```

should be
```
def dynamic_df_country_pop():
  # Create a dataframe
  new_df = pd.DataFrame()
  # Call code to fill dataframe with updated datas
  # .... 
  return new_df 
```

This way, you will get the new data on each tableau extract. Take care to always return the same dataframe format (no new columns or dtypes difference...)

Regards

**Comment by btribonde** [comment]
By the way, I was looking at your github profile. Did you create https://public.tableau.com/profile/dennis.ganzaroli#!/vizhome/Covid_19_15859211442940/dsh_anim using Jupytab ?

**Comment by deganza** [comment]
Thank you!
I will test it with the covid data of tomorrow.
Yes I made this dashboard and also the following video
https://youtu.be/lbmeKhZuXiI


btribonde <notifications@github.com> schrieb am Do., 7. Mai 2020, 17:57:

**Comment by deganza** [comment]
it seem's to work. I had just to refresh the datasource.
But there is no way that the Tableau-Files are refreshed when the data is updated?

**Comment by btribonde** [comment]
Glad it worked.

No, sorry i dont know any way to do this. Maybe using an external tableau api to trigger à refresh ? This is probably what I would look for.

May I considère this issue closed ?

**Comment by deganza** [comment]
yes issue is resolved. Thank you!

**Comment by deganza** [comment]
sorry but it's still not working.
I've still to "restart kernel" and "Explore in Tableau" before I refresh the datasource.
The only way to refresh the data directly is by restarting jupytab with the config.ini

**Comment by btribonde** [comment]
Hello,

You can try with the following notebook:

```
def dynamic_df():
    return pd.DataFrame(np.random.random((3, 3)), columns=['a', 'b', 'c'])

tables = jupytab.Tables()  # Publication-ready tables contained by this notebook

# Example 2: Dynamic data: a new DataFrame is generated whenever Extract is requested on Tableau's side:
tables['dynamic'] = jupytab.DataFrameTable('A dynamic table', refresh_method=dynamic_df)
```

In my tableau desktop, data is refreshed on each 'Refresh Data Source' action. Could you try with this one ?

**Comment by deganza** [comment]
Hi

It's not working. I got the new Notebook Connector (Jupytab_Test) but then the connection hangs on. 
In the terminal I get the following error: ConnectionRefusedError: [Errno 111] Connection refused
![jupy1](https://user-images.githubusercontent.com/42083662/82351792-58929b00-99fd-11ea-844f-32a3ce923f28.jpg)
![jupy2](https://user-images.githubusercontent.com/42083662/82351803-5d574f00-99fd-11ea-8f9d-431debb3c1f7.jpg)
![jupy3](https://user-images.githubusercontent.com/42083662/82351816-61836c80-99fd-11ea-9556-eea51e464916.jpg)

**Comment by btribonde** [comment]
Hello, I don't see the notebook informations in the top screen provided (Notebook to Tableau connector). This is usually the case if the token is not provided (or not the expected one).

In the web app, are you able to visualize the schema ? (using the provided button along the explore in tableau one).

**Comment by deganza** [comment]
The token is ok but I'm not able to visualize the Jupytab_Test Notebook
![jupy4](https://user-images.githubusercontent.com/42083662/82409647-849a3480-9a6e-11ea-931b-c68fbb13b2e2.jpg)

**Comment by btribonde** [comment]
Hello, could you attach the notebook Jupytab_Test, this would help to diagnose.

By the way, I need to add lot more debug informations in console and webapp :)

**Comment by btribonde** [comment]
Hello @deganza 

I've been able to reproduce your problem, however reinstalling the jupytab environment with pip fixed it. It seems that kernel gateway was not able to correctly start the notebook in http mode. I checked the library version but I've not been able to find the exact problem.

Regards

**Comment by deganza** [comment]
thanks a lot! I've reinstalled jupytab and it seems to work better for my Covid19_Tableau Notebook.
But for the other one I've still some trouble. I put you the notebook in the attachment. Maybe you see something.

[Jupytab_Test.ipynb.zip](https://github.com/CFMTech/Jupytab/files/4679965/Jupytab_Test.ipynb.zip)

**Comment by btribonde** [comment]
Notebook is missing mandatory imports : 
```
import pandas as pd
import numpy as np
```
and is also missing the two #get /schema and /data cells. But usage of the DataFrameTable seems ok.

**Comment by deganza** [comment]
Fantastic!!!
Now it's working and I've just to refresh the datasource in the sheet.
Thanks a lot!

**Comment by btribonde** [comment]
You're welcome :)

I close this issue, do not hesitate to open a new one for bug or feature request.

**Comment by deganza** [comment]
Hi 
I've again the same problem. I've still to restart the kernel to update the data in tableau.
