### ISSUE TITLE
dynamic_df() instead of static_df() in readme

### ISSUE THREAD

**Issue by polinas123** [CFMTech/Jupytab#48]
possible typo in readme?
here
`# Example 1: Static data: it will never change on the Tableau side:
static_df = dynamic_df()`
and here
`# Example 3: Static data with index included
static_df = dynamic_df()`
shouldn't it be 'static_df = static_df()'?

**Comment by btribonde** [comment]
Hello,

Thanks for your feedback, but this is not a typo.

dynamic_df is a python method defined above that creates a dataframe, so it actually creates a static dataframe once it has been invoked.

However, if i want jupytab to refresh the dataframe on tableau extract, I will give the method handler: dynamic_df without the () operator.

Regards
